version: '3.9'

services:
    vocabulary-builder:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - '8000:8000'
        env_file:
            - .env
        volumes:
            - ./vocabulary_builder:/app/vocabulary_builder:ro
            - ./locales:/app/locales:ro
            - .env:/app/env:ro
        depends_on:
            - db

    db:
        image: postgres:13
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'

volumes:
    pgdata:
