version: '3.9'

services:
    vocabulary-builder:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - '8000:8000'
        env_file:
            - .env
        volumes:
            - .:/opt/app
            - ./test.db:/app/test.db
        depends_on:
            - db

    db:
        image: nouchka/sqlite3
        volumes:
            - ./test.db:/data/test.db
