"""Update WordModel with UUID default

Revision ID: 134106b1ca86
Revises: 6c66a9f9d49b
Create Date: 2024-06-01 11:14:36.594095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '134106b1ca86'
down_revision: Union[str, None] = '6c66a9f9d49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'id',
                    existing_type=sa.Uuid(),
                    nullable=False,
                    server_default=sa.text("uuid_generate_v4()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'id',
                    existing_type=sa.Uuid(),
                    nullable=False,
                    server_default=None)
    # ### end Alembic commands ###
