"""Initial migration

Revision ID: 41d5732008ad
Revises:
Create Date: 2024-06-24 18:06:50.969367

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "41d5732008ad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("part_of_speech", sa.String(), nullable=False),
        sa.Column("transcription", sa.String(), nullable=False),
        sa.Column("audio", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meanings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("word_id", sa.Uuid(), nullable=False),
        sa.Column("meaning", sa.String(), nullable=False),
        sa.Column("meaning_language", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "examples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meaning_id", sa.Uuid(), nullable=False),
        sa.Column("example", sa.String(), nullable=False),
        sa.Column("example_translation", sa.String(), nullable=False),
        sa.Column("example_translation_language", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meaning_id"],
            ["meanings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("examples")
    op.drop_table("meanings")
    op.drop_table("words")
    op.drop_table("users")
    # ### end Alembic commands ###
