"""Initial migration

Revision ID: 6c66a9f9d49b
Revises:
Create Date: 2024-05-31 23:37:59.088137

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6c66a9f9d49b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("translated_word", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("translated_context", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("words")
    # ### end Alembic commands ###
